scrapinghub/scrapy-poet

- README.rst
- tox.ini
a new version of scrapy was released with a code that we need for finding spider callbacks
> Update Scrapy version/dependency

- README.rst
Referencing docs instead of duplicating content.
> Simplify readme file to avoid duplication

- README.rst
Hey! I've fixed docs build and added a badge to readme.
> add a badge with docs build status to the readme

- docs/index.rst
I think we were mistaking web-poet's goal with scrapy-poet's.
> Fix project goal on docs

- .travis.yml
- docs/conf.py
- tox.ini
Add docs configuration to `tox.ini`
Run the configuration in travis.
Had to fix the static path that was breaking the build
> Feat tox docs

- .travis.yml
- README.rst
This should fix issues with travis ci and pypi pushing after the rename of scrapy-po to scrapy-poet
> Switch PYPI key

- example/example/autoextract.py
- scrapy_poet/middleware.py
- tests/utils.py
> returnValue is only needed for Python 2

- docs/intro/tutorial.rst
Documentation updated:
- fixed typo (broken example)
- fixed links selector.
> [documentation] Add required imports/fix typo.

- docs/intro/advanced-tutorial.rst
- tests/test_downloader.py
Related to https://github.com/scrapinghub/web-poet/pull/76
> rename "http_client" var to "http" in doc examples

- .bumpversion.cfg
- CHANGELOG.rst
- docs/conf.py
- setup.py
> Prepare 0.6.0 release

- pyproject.toml
- scrapy_poet/page_input_providers.py
- tests/test_cache.py
> fix bug by passing spider instance to to_dict( ... ) method of scrapy Request

- CHANGELOG.rst
- scrapy_poet/downloadermiddlewares.py
- tests/test_middleware.py
- tests/test_retries.py
Fixes:
- https://github.com/scrapinghub/scrapy-poet/issues/112
Also kind of related to:
- https://github.com/scrapinghub/scrapy-poet/issues/98
- https://github.com/scrapinghub/scrapy-poet/issues/110
> fix `web_poet.exceptions.Retry` not working

- CHANGELOG.rst
Hey! I tried to simplify the changelog entry a bit, to put the recommendations first.
> simplify changelog entry related to GH-106

- docs/intro/advanced-tutorial.rst
- docs/intro/basic-tutorial.rst
- docs/intro/pitfalls.rst
- docs/providers.rst
- docs/rules-from-web-poet.rst
- scrapy_poet/api.py
- scrapy_poet/downloadermiddlewares.py
- scrapy_poet/injection.py
- scrapy_poet/page_input_providers.py
Ignore the failing tests, it's because of https://github.com/scrapinghub/web-poet/pull/124 which was included in the latest **web-poet** release.
It's fixed in https://github.com/scrapinghub/scrapy-poet/pull/120.
> doc improvements

- scrapy_poet/commands.py
- scrapy_poet/page_input_providers.py
- setup.py
- tests/test_commands.py
Based on https://github.com/scrapinghub/web-poet/pull/128
> Support HttpClient in savefixture

- tests/test_web_poet_rules.py
Found by new flake8-comprehensions
> Fix any() calls with lists

- scrapy_poet/injection.py
- tests/test_middleware.py
> Fix scrapy shell with InjectionMiddleware

- docs/providers.rst
It ain't much, but it's honest work
> Fix typo in docs

- CHANGELOG.rst
To follow https://github.com/scrapinghub/scrapy-poet/pull/159.
> Cover 0.15.0 in the changelog

- README.rst
- docs/intro/advanced-tutorial.rst
- docs/intro/install.rst
- example/example/settings.py
- scrapy_poet/__init__.py
- scrapy_poet/downloadermiddlewares.py
- scrapy_poet/utils/testing.py
- tests/conftest.py
- tests/test_cache.py
- tests/test_downloader.py
- tests/test_middleware.py
- tests/test_request_fingerprinter.py
- tests/test_retries.py
- tests/test_web_poet_rules.py
Fixes https://github.com/scrapy-plugins/scrapy-zyte-api/issues/112 (the remaining second half)
> Do not count DummyResponse into downloader stats

- CHANGELOG.rst
> Release notes for 0.22.6

- CHANGELOG.rst
I’m not quite happy about the last bullet point warning :expressionless:
> Release notes for 0.25.0

- docs/settings.rst
- scrapy_poet/middleware.py
- scrapy_poet/page_input_providers.py
- scrapy_poet/utils/__init__.py
- tests/test_middleware.py
- tests/test_page_input_providers.py
- tests/test_providers.py
> Remove deprecated code.
