scrapinghub/scrapy-poet

scrapy_po/webpage.py

This is backwards incompatible: ItemPage doesn't provide selector
shortcuts anymore, and so it doesn't require a response.

Extract selector-specific logic to a mixin.

---

README.rst
example/example/autoextract.py
example/example/settings.py
example/example/spiders/books_06.py
scrapy_po/__init__.py
scrapy_po/middleware.py
scrapy_po/webpage.py

Question: is the name too long (`PageComponent`)? 
Alternatives::
* `Component`
* `PagePart`
* `PagePiece`
Note this is based on top of https://github.com/scrapinghub/scrapy-po/pull/5 that is in the review process.

PageComponent introduced

---

example/example/autoextract.py
example/example/spiders/books_05_1.py
scrapy_po/middleware.py
scrapy_po/page_input_providers.py
scrapy_po/utils.py
tests/test_middleware.py
tests/test_utils.py
tests/utils.py

This is done by inspecting parsers and injectable dependencies.
We search for type annotations and the use of DummyRequests.

Skipping downloads when they're not necessary to execute parsers

---

docs/advanced.rst
docs/api_reference.rst
docs/intro/tutorial.rst

This PR has small changes to the existing docs;  see commit messages for more detailed list of changes.
I think the version we have here is not final, it seems there are still things to improve:
* tutorial doesn't provide enough motivation - it shows what to do, but fails to explain why
* tutorial doesn't go far enough (e.g. no listing page objects) -  but it only makes sense to have these sections after fixing the "motivation" bit
* advanced docs may need to be split up for docs needed to provider writers and docs needed for the users. Currently it is written for provider writers, but it seems e.g. DummyResponse can be  explained in a simpler way for people who just need to use it.
I haven't touched those, let's keep if out of scope for this PR.

Documentation follow-up

---

docs/advanced.rst
docs/conf.py
docs/index.rst
docs/intro/install.rst
docs/intro/tutorial.rst
scrapy_poet/utils.py

TODO:
I've made minor changes here and there, and added more links to web-poet docs. There are still sections can be explained a bit better (e.g. DummyResponse, from an user point of view), but I think this can be done later; having integrations available in third-party packages (e.g. for Splash and AutoExtract) could also allow to make the docs better later.

improve documentation

---

scrapy_poet/middleware.py

Fixes GH-47.
Before:
> 2021-05-30 00:16:51 [category] DEBUG: Skipping download of <GET https://www.example.com/products/eacs-i-09harx-n3-20061030>
After:
> 2021-05-31 01:42:27 [scrapy_poet.middleware] DEBUG: Using DummyResponse instead of downloading <GET https://www.example.com/products/eacs-i-09harx-n3-20061030>

Improve logging message for DummyResponse. 

---

CHANGELOG.rst
docs/api_reference.rst
docs/index.rst
docs/intro/install.rst
docs/intro/tutorial.rst
docs/overrides.rst
docs/providers.rst
docs/settings.rst
scrapy_poet/__init__.py
scrapy_poet/cache.py
scrapy_poet/injection.py
scrapy_poet/middleware.py
scrapy_poet/page_input_providers.py
scrapy_poet/utils.py
setup.py
tests/test_injection.py
tests/test_middleware.py
tests/test_providers.py

New providers interface
Error caching can be enabled or disabled.
Compression can be enabled or disabled.
Avoiding having key conflicts between provides was done by adding prefix to each key. It would be more efficient to have a separate table per provider in the sqlite database. I leave this for the future.
Todo:
**Possible documentation schema**:
It can be a new section "Cache" in the `ADVANCED` section. 
1.  What is the cache
2. A simple example enabling the cache
3. Cache configuration
3.1 Simple mode (setting it to TRUE)
3.2 Custom cache file (setting a custom file for the cache)
3.3 GZIP compression enable/disable (enabled by default)
3.4. Cache errors. Why. Disabled by default.
The "Providers" section should be updated. It should include:
* How to create providers that can be …

SCRAPY_POET_CACHE mechanism

---

README.rst

Accessing http://scrapy-poet.readthedocs.io is not possible, as redirection to https does not always happen automatically. This PR fixes the issue.

docs: update docs urls to use https

---

docs/index.rst

The sentence: *"Concrete integrations are not provided by ``scrapy-poet``, but
``scrapy-poet`` makes them possbile."* is unclear, contradictory even.
This PR proposes a fix by reformulating the sentence to:
*"Concrete integrations are not provided by ``web-poet``, but
``scrapy-poet`` makes them possbile."*

docs: Fix unclear sentence in docs intro

---

docs/intro/install.rst

The page https://github.com/scrapinghub/parsel does not exist.
This PR fixes the link to https://github.com/scrapy/parsel.

docs: fix broken link to `parsel`

---

CHANGELOG.rst
docs/overrides.rst
docs/providers.rst
scrapy_poet/__init__.py
scrapy_poet/middleware.py
scrapy_poet/page_input_providers.py
setup.py
tests/conftest.py
tests/test_injection.py
tests/test_middleware.py
tests/test_providers.py
tests/test_response_required_logic.py
tests/test_scrapy_dependencies.py
tox.ini

Reference PR from `web_poet`: https://github.com/scrapinghub/web-poet/pull/30.
This also uses the small enhancement in https://github.com/scrapinghub/web-poet/pull/33.

Use the new HttpResponse that replaces ResponseData in web_poet

---

scrapy_poet/page_input_providers.py

Reference: https://github.com/scrapinghub/scrapy-poet/pull/67#discussion_r867212146
Removing the need for this alternative constructor call since `HttpResponseHeaders` has been serialized correctly. Calling `HttpResponseHeaders.from_bytes_dict(response_data["headers"])` would be redundant.

remove from_bytes_dict() call when deserializing responses

---

docs/intro/basic-tutorial.rst
scrapy_poet/api.py

Built on top of https://github.com/scrapinghub/scrapy-poet/pull/62.
I just noticed that the examples were incorrect or at least was not clear enough.

Fix doc examples on callback_for()

---

docs/intro/advanced-tutorial.rst
docs/intro/basic-tutorial.rst
docs/providers.rst
scrapy_poet/api.py

Very minor.
I noticed this when writing a talk for POs wherein copying code from the official docs renders inconsistent quotes in the code. I've chosen double quotes on this PR since we use Black, making the docs consistent with the code and tests.

update docs/docstrings to consistently use double quotes

---

scrapy_poet/downloader.py

I think `scrapy.exceptions.IgnoreRequest` only works because some other Scrapy code imports scrapy.exceptions. While it's unlikely to break, I think it's better to use an explicit import.

avoid using scrapy.exceptions which is not imported explicitly

---

CHANGELOG.rst
docs/intro/advanced-tutorial.rst
docs/intro/basic-tutorial.rst
docs/overrides.rst
docs/providers.rst
example/example/spiders/books_02.py
example/example/spiders/books_02_1.py
example/example/spiders/books_02_2.py
example/example/spiders/books_02_3.py
example/example/spiders/books_04.py
example/example/spiders/books_04_overrides_01.py
example/example/spiders/books_04_overrides_02.py
example/example/spiders/books_04_overrides_03.py
example/example/spiders/books_06.py
pyproject.toml
scrapy_poet/api.py
scrapy_poet/cache.py
scrapy_poet/injection.py
scrapy_poet/overrides.py
setup.py
tests/po_lib/__init__.py
tests/test_callback_for.py
tests/test_downloader.py
tests/test_injection.py
tests/test_middleware.py
tests/test_retries.py
tests/test_scrapy_dependencies.py
tox.ini

Migration away from the deprecated functionalities of **web-poet** as introduced in https://github.com/scrapinghub/web-poet/pull/84.
This PR should not receive any `DeprecationWarning` from **web-poet**.

Moving away from upcoming deprecated functionalities of web-poet==0.6.0

---

docs/intro/basic-tutorial.rst
docs/intro/install.rst

Our `settings.py` config is tucked away in another page, adding some friction on how users could quickly set it up in their projects.

improve visibility of settings.py config in the docs

---

tox.ini

The issue was due to a new tox v4 which has some backward incompatible changes.

fix failing 'docs' CI env

---

.github/workflows/test.yml
CHANGELOG.rst
setup.py
tox.ini

I'm excited to have better error message in our CI as per this new feature: https://docs.python.org/3/whatsnew/3.11.html#pep-657-fine-grained-error-locations-in-tracebacks

official support for Python 3.11

---

tox.ini

In the past few weeks, a fix in https://github.com/scrapinghub/scrapy-poet/pull/101 has been created to fix the failing CI due to the new tox v4 release.
After some time, tox released another update which causes our **docs** env to not build the sphinx docs but instead run the unit tests. Reference: https://github.com/scrapinghub/scrapy-poet/actions/runs/3827563316/jobs/6512254767

tox: declare 'testenv' in docs

---

docs/requirements.txt

This fixes some of the bullet point formatting issues in our docs.
---
---

bump doc dep sphinx-td-theme 0.4 → 1.1.0

---

tests/test_web_poet_rules.py

fix failing tests after new warning phrases for dupe rules

---

CHANGELOG.rst
docs/intro/basic-tutorial.rst
docs/rules-from-web-poet.rst
docs/settings.rst
scrapy_poet/utils/__init__.py
tests/test_downloader.py
tests/test_utils.py
tests/test_web_poet_rules.py

Stemming from the discussion in https://github.com/scrapinghub/scrapy-poet/pull/119#discussion_r1093194207.
~Also addresses the failing tests as mentioned in https://github.com/scrapinghub/scrapy-poet/issues/123.~  Moved into another PR: https://github.com/scrapinghub/scrapy-poet/pull/125

Default: `SCRAPY_POET_RULES = web_poet.default_registry.get_rules()`

---

.github/workflows/test.yml
CHANGELOG.rst
scrapy_poet/commands.py
scrapy_poet/downloadermiddlewares.py
scrapy_poet/page_input_providers.py
scrapy_poet/spidermiddlewares.py
tests/__init__.py
tests/test_web_poet_rules.py
tox.ini

Built on top of #126 since it needs the `is_min_scrapy_version()` utility function.
These changes are necessary since otherwise, GitHub actions was not using some of the pinned configurations of `min`, `asyncio`, and `asyncio-min`.
For example, `min` was not using `scrapy==2.6.0` but the latest version at the current time: [https://github.com/scrapinghub/scrapy-poet/actions/runs/4047094013/jobs/6960692434](https://github.com/scrapinghub/scrapy-poet/actions/runs/4047094013/jobs/6960692434)

Fix CI failing on `min`, `asyncio`, and `asyncio-min` envs

---

scrapy_poet/commands.py

As initializing and downloading is no longer done while the time machine time is ticking, this should help greatly with time differences in the field values.
On the other hand, I'm now not sure how will we be able to switch to running real project spiders in savefixture instead of `InjectableSpider`, maybe it will be possible by moving the time machine part into some deeper scrapy-poet code.

Only run to_item() under the time machine

---

.readthedocs.yml

Fixes failing build in [https://readthedocs.org/projects/scrapy-poet/builds/19661918/](https://readthedocs.org/projects/scrapy-poet/builds/19661918/) since it's not using Python 3.7 which `async-lru` doesn't support
Related to https://github.com/scrapinghub/web-poet/pull/147

add .readthedocs.yml config

---

docs/intro/pitfalls.rst
scrapy_poet/utils/__init__.py
tests/test_utils.py

Fixes https://github.com/scrapinghub/scrapy-poet/issues/91
The error:
```
open_in_browser(po.response)
Traceback (most recent call last):
File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
exec(exp, global_vars, local_vars)
File "<input>", line 1, in <module>
File "/Users/bulat/PycharmProjects/zyteprojects/envs/web-poet/lib/python3.10/site-packages/scrapy/utils/response.py", line 101, in open_in_browser
raise TypeError("Unsupported response type: " f"{response.__class__.__name__}")
TypeError: Unsupported response type: HttpResponse
```

Amend scrapy open_in_browser tool.

---

scrapy_poet/commands.py
scrapy_poet/downloadermiddlewares.py
scrapy_poet/injection.py
scrapy_poet/page_input_providers.py
setup.py
tests/test_response_required_logic.py
tests/test_web_poet_rules.py
tox.ini

Fixes the case when the following code below results in a `ProviderDependencyDeadlockError`. In this example, the issue stems from the `product: Product` dependency that's declared. However, **scrapy-poet** sees `ProductPage` as the one that provides it which causes the deadlock error.
```python
import attrs
from zyte_common_items import Product
from web_poet import handle_urls, WebPage
@handle_urls("example.com")
@attrs.define 
class ProductPage(WebPage[Product]):
product: Product
def name(self) -> str:
return f"(modified) {self.product.name}"
```
The use case for this is when items like `Product` are produced by a provider and not a page object. For example, **scrapy-zyte-api**'s `ZyteApiProvider` ([reference](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/pr …

Handle item overrides

---

scrapy_poet/utils/__init__.py
tests/test_downloader.py
tests/test_utils.py

This should fix https://github.com/scrapy-plugins/scrapy-zyte-api/issues/135, not sure if any additional tests in any components are needed.

Set NO_CALLBACK for HttpClientProvider requests.

---

scrapy_poet/page_input_providers.py
setup.py
tests/test_providers.py
tox.ini

To mirror response counterparts, I only implemented a provider for `HttpRequest`, and not for `HttpRequestBody` or `HttpRequestHeaders`. Is that OK, or should we provide more granular providers? It would be trivial to do, but if we do I wonder if I should do the same with response page input classes as well.
To-do:

Add HttpRequestProvider

---

tests/test_web_poet_rules.py

Unless I'm missing something the existing code is a no-op: the generator expression produces True for correct deps and nothing for incorrect ones.

Fix logic in assert_deps.

---

scrapy_poet/_request_fingerprinter.py
scrapy_poet/utils/testing.py
tests/test_request_fingerprinter.py

Required by https://github.com/scrapy-plugins/scrapy-zyte-api/pull/165.
To do:

Fixes related to upcoming scrapy-zyte-api request fingerprinting work

---

docs/providers.rst
scrapy_poet/injection.py
tests/test_injection.py

Currently, `SCRAPY_POET_CACHE` can be set to `True` to allow scrapy-poet to save instances created by providers locally. By default, this is turned off.
I'm proposing to introduce an `Injector.weak_cache` that would have its instances stored in memory and be removed when the corresponding `Request` instance is no longer available. By default, this is turned on. The motivation for this is to allow sharing of instances between providers by default without the risk of accumulating large number of instances locally which can result in running out of disk space.
This also means that the weakref cache mechanism in **ZyteApiProvider** ([code ref](https://github.com/scrapy-plugins/scrapy-zyte-api/blob/main/scrapy_zyte_api/providers.py#L48)) can be removed as it can use this new `.weak_cache` …

create a weak_cache in Injector

---

scrapy_poet/injection.py
tests/test_response_required_logic.py

Fixes https://github.com/scrapy-plugins/scrapy-zyte-api/issues/170.
TIL about https://peps.python.org/pep-0649/.

Fix DummyResponse detection when using strings as annotations

---

docs/providers.rst
scrapy_poet/__init__.py
scrapy_poet/api.py
scrapy_poet/commands.py
scrapy_poet/injection.py
scrapy_poet/utils/mockserver.py
setup.py
tests/test_commands.py
tests/test_injection.py
tox.ini

Requires https://github.com/scrapinghub/web-poet/pull/201

Add support for annotated deps in savefixture.

---

scrapy_poet/downloadermiddlewares.py
tests/test_page_input_providers.py

@fcanobrash found out it was not working.
Workaround for earlier versions (it was added in 0.17.0):
```python
from scrapy_poet.page_input_providers import HttpRequestProvider
SCRAPY_POET_PROVIDERS = {
HttpRequestProvider: 400,
}
```

Enable HttpRequestProvider by default

---

scrapy_poet/utils/testing.py

This was causing the provider-specific test failures in https://github.com/scrapy-plugins/scrapy-zyte-api/pull/155

make_crawler: do not change setting priorities

---

scrapy_poet/spidermiddlewares.py
tests/test_retries.py
tox.ini

If Retry has a message, use it as retry reason

---

scrapy_poet/injection.py
tests/test_injection.py

A quick fix for a regression in #207 that raised an exception for annotated types.
The proper annotated dynamic deps support including support for multiple annotated deps requires some refactoring and logic changes and will be done separately.
Edit: as the most basic fix doesn't work on 3.9 I added a better one that includes support for multiple annotated deps but not other things that are still needed.
Edit 2: here is hopefully the complete fix, with making the results not annotated.

Restore and improve the annotated dynamic deps support.

---

tox.ini

Some tests hang with new Scrapy due to https://github.com/scrapy/scrapy/issues/6784

Fix CI (pin older Scrapy).
